v0.2.0

diff --git a/sensitive_domain_search b/sensitive_domain_search
--- a/sensitive_domain_search
+++ b/sensitive_domain_search
@@ -1,16 +1,10 @@
 #!/bin/bash
-###
-###  pipeline_for_high_sensitive_domain_search - a helper tool for high sensitive HMM-HMM search against Pfam using HHsearch and JackHMMER
-###
-###    Copyright: 2018 (C) Yosuke Nishimura (yosuke@kuicr.kyoto-u.ac.jp)
-###    License: MIT license
-###
 
 PROGNAME=$(basename $0)
-VERSION="0.1.3"
+VERSION="0.2.0"
 Errmsg="[1;31m[error][0m"
 Sccmsg="[1;32m[success][0m"
-Modidate="2019-07-29"
+Modidate="2023-04-20"
 incmd="$0 $*"
 numWord=$(echo $incmd |wc -w)
 
@@ -20,9 +14,14 @@ read -r -d '' usage <<EOF
 [1;35m### $PROGNAME ver $VERSION ($Modidate) ###[0m
 
 [32m[description][0m
-$PROGNAME - a helper tool for high sensitive HMM-HMM search against Pfam using HHsearch and JackHMMER
+$PROGNAME - a helper tool for high sensitive HMM-HMM search against domain DBs (e.g. Pfam) using either (a) HHblits or (b) HHsearch and JackHMMER
+Default is HHblits, changed from ver 0.2.0 (2023-04-20).
 
 [32m[reference][0m
+(mode hhblits)
+HHblits   - doi:10.1038/nmeth.1818
+
+(mode hhsearch)
 HHsearch  - doi:10.1093/bioinformatics/bti125
 JackHMMER - doi:10.1186/1471-2105-11-431
 
@@ -30,44 +29,55 @@ JackHMMER - doi:10.1186/1471-2105-11-431
 $ $PROGNAME [options]
 
 [32m[dependencies][0m
+    - ruby (ver >=2.1) 
+    (mode hhblits)
+    - hhblits               -- included in the HHsuite package;
+                               HHsuite3 - https://github.com/soedinglab/hh-suite
+    (mode hhsearch)
     - jackhmmer             -- included in the HMMER3 package;
                                http://hmmer.org/
     - hhsearch, reformat.pl -- included in the HHsuite package;
                                HHsuite3 - https://github.com/soedinglab/hh-suite
                                HHsuite2 - http://wwwuser.gwdg.de/~compbiol/data/hhsuite/releases/all/
-    - ruby (ver >=2.1) 
 
 [32m[options][0m
   (general)
     -i, --in      [path]  (required) query protein fasta file. To use multiple files as input, this value could be (1) comma-separeted file paths or (2) path of input file list (one file in one line).
                           If many proteins are included in a fasta file, adding "belongTo:" tag in comment lines to generate easy-to-understand output.  e.g. ">protein1 len:200 belongTo:contig1"
     -o, --out     [path]  (required) output directory. It should not exist.
-    -J, --jackdb  [path]  (required) protein fasta file to create query HMM with query proteins, used as database sequences for JackHMMER
     -H, --hhdb    [path]  (required) Pfam database for HHsearch available here: http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/
+    -m, --mode    [hhblits or hhsearch] search mode. (default: hhblits)
+    -J, --jackdb  [path]  (required for mode hhsearch) protein fasta file to create query HMM with query proteins, used as database sequences for JackHMMER
     -h, --help
     -v, --version
 
-  (jackhmmer related)
+  (for hhblits)
+    -N, --iter    [int]   (default: 5) number of iteration of hhblits
+        --evalue  [num]   (default: 10) E-value threshold for inclusion in a result table
+        --pvalue  [num]   (default: 1)  P-value threshold for inclusion in a result table
+        --prob    [num]   (default: 30) %-Probability threshold for inclusion in a result table
+
+  (for jackhmmer)
     -N, --iter    [int]   (default: 5) number of iteration of JackHMMER serach
         --incE    [num]   (default: 0.001) inclusion threshold for sequences
         --incdomE [num]   (default: 0.001) inclusion threshold for domains
 
-  (hhsearch related)
+  (for hhsearch related)
     -n, --nreport [int]   (default: 3)  number of hits for each query shown in a result table
         --evalue  [num]   (default: 10) E-value threshold for inclusion in a result table
         --pvalue  [num]   (default: 1)  P-value threshold for inclusion in a result table
         --prob    [num]   (default: 30) %-Probability threshold for inclusion in a result table
 
-  (use GNU parallel)
-        --ncpus   [int]   -- number of simaltaneous jobs
+  (for multiple cpu computation)
+        --ncpus   [int]   -- number of simaltaneous jobs (using GNU Parallel)
 
   (for icr user)          for computation in the ICR supercomputer system
         --queue   [JP1]   -- queue to calculate
 
 [32m[output files][0m
-result/<input file name>/<group>/besthit.tsv   -- table of HHserach besthit. See README.md for column description. Group is what is specified by the "belongTo:" tags or "ungrouped" if not provided (see description of the -i/--in option).
-result/<input file name>/<group>/top<n>hit.tsv -- table of HHserach top<n>hit. <n> can be altered by -n/--nreport option (default: 3).
-work/<input file name>/<group>/<protein>/      -- The directory includes all the output files of jackhmmer and hhsearch
+result/<input file name>/<group>/besthit.tsv   -- table of besthit. See README.md for column description. Group is what is specified by the "belongTo:" tags or "ungrouped" if not provided (see description of the -i/--in option).
+result/<input file name>/<group>/top<n>hit.tsv -- table of top<n>hit. <n> can be altered by -n/--nreport option (default: 3).
+work/<input file name>/<group>/<protein>/      -- The directory includes all the output files
 info/stats.txt                                 -- number of proteins in each file
 EOF
 # }}} usage
@@ -85,6 +95,10 @@ do
 			echo $VERSION
 			exit 1
 			;;
+		'--overwrite' )
+			overwrite=true
+			shift 1
+			;;
 		'-i'|'--in' )
 			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
 				echo "$Errmsg option requires an argument -- $1" 1>&2
@@ -99,6 +113,14 @@ do
 				exit 1
 			fi
 			dir="$2"
+			shift 2
+			;;
+		'-m'|'--mode' )
+			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
+				echo "$Errmsg option requires an argument -- $1" 1>&2
+				exit 1
+			fi
+			mode="$2"
 			shift 2
 			;;
 		'-J'|'--jackdb' )
@@ -218,29 +240,35 @@ done
 
 
 # {{{ validate input command/arguments
+
+### default of mode
+if [ -z "$mode" ] ; then
+	mode="hhblits"
+fi
+### default of nreport
+nreport="${nreport:-3}"
+
 if [ $numWord -eq 1 ] ; then ## case when no argument is given.
 	echo "$usage"
 	exit 1
-elif [ -e "$dir" ] ; then
-	echo "$Errmsg output directory already exists." 1>&2
-	exit 1
+elif [[ ! -n "$dir" ]] ; then
+	echo "$Errmsg  -o, --out should be given." 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
+elif [[   -d "$dir" && -z "$overwrite" ]] ; then
+	echo "$Errmsg  -o, --out $dir already exists. Use --overwrite to overwrite it. " 1>&2; echo "         execute '$PROGNAME -h' for usage" 1>&2; exit 1
 elif [ -n "$params" ] ; then
 	echo "$Errmsg some argument detected. Need no argument." 1>&2
 	exit 1
 elif [ -z "$in" ] ; then
 	echo "$Errmsg query protein sequence should be specified ('-i' or '--in')" 1>&2
 	exit 1
-elif [ -z "$dir" ] ; then
-	echo "$Errmsg output directory should be specified ('-o' or '--out')" 1>&2
-	exit 1
-elif [ -z "$jackdb" ] ; then
+elif [[ -z "$jackdb" && "$mode" == "hhsearch" ]] ; then
 	echo "$Errmsg protein fasta file for jackhmmer database should be specified ('-J' or '--jackdb')" 1>&2
 	exit 1
-elif [ ! -f "$jackdb" ] ; then
+elif [[ ! -f "$jackdb" && "$mode" == "hhsearch" ]] ; then
 	echo "$Errmsg protein fasta file for jackhmmer database should exist" 1>&2
 	exit 1
 elif [ -z "$hhdb" ] ; then
-	echo "$Errmsg database file for hhsearch should be specified ('-H' or '--hhdb')" 1>&2
+	echo "$Errmsg database file for $mode should be specified ('-H' or '--hhdb')" 1>&2
 	exit 1
 # elif [ ! -f "${hhdb}_hhm_db" ] ; then
 # 	echo "$Errmsg ${hhdb}_hhm.db should exist" 1>&2
@@ -248,7 +276,7 @@ elif [ -z "$hhdb" ] ; then
 elif [ ! -f "${hhdb}_hhm.ffdata" ] ; then
 	echo "$Errmsg ${hhdb}_hhm.ffdata should exist" 1>&2
 	exit 1
-elif [ "$nreport" -lt 1 ] ; then
+elif [[ "$nreport" -lt 1 ]] ; then
 	echo "$Errmsg $nreport should be equal to or more than 1." 1>&2
 	exit 1
 elif ! [ -f "$in" ] ; then ## input file is not detected --> validate comma separated multiple files
@@ -264,9 +292,14 @@ fi
 
 # {{{ check dependencies
 ### check availablity of commands of HMMER3/HHsuite
-command -v jackhmmer   >/dev/null 2>&1 || { echo >&2 "$Errmsg jackhmmer (in HMMER3 package) is required but not available.  Aborting."; exit 1; }
-command -v hhsearch    >/dev/null 2>&1 || { echo >&2 "$Errmsg hhsearch (in HHsuite package) is required but not available.  Aborting."; exit 1; }
-command -v reformat.pl >/dev/null 2>&1 || { echo >&2 "$Errmsg reformat.pl (in HHsuite package) is required but not available.  Aborting."; exit 1; }
+if [ "$mode" == "hhblits" ] ; then
+	command -v hhblits     >/dev/null 2>&1 || { echo >&2 "$Errmsg hhblits  (in HHsuite package) is required but not available.  Aborting."; exit 1; }
+fi
+if [ "$mode" == "hhsearch" ] ; then
+	command -v jackhmmer   >/dev/null 2>&1 || { echo >&2 "$Errmsg jackhmmer (in HMMER3 package) is required but not available.  Aborting."; exit 1; }
+	command -v hhsearch    >/dev/null 2>&1 || { echo >&2 "$Errmsg hhsearch (in HHsuite package) is required but not available.  Aborting."; exit 1; }
+	command -v reformat.pl >/dev/null 2>&1 || { echo >&2 "$Errmsg reformat.pl (in HHsuite package) is required but not available.  Aborting."; exit 1; }
+fi
 
 ### check ruby version
 ST=`ruby -e 'print RUBY_VERSION.to_f >= 2.1 ? 0 : 1'`
@@ -291,8 +324,6 @@ iter="${iter:-5}"
 incE="${incE:-0.001}"
 incdomE="${incdomE:-0.001}"
 
-### thresholds (hhsearch)
-nreport="${nreport:-3}"
 ## [ref: hhsuite-userguide.pdf] Roughly speaking, one should give a hit serious consideration (i.e., check the other points in this list) whenever (1) the hit has > 50% probability, or (2) it has > 30% probability and is among the top three hits.
 evalue="${evalue:-10}"
 pvalue="${pvalue:-1}"
@@ -350,7 +381,7 @@ echo "$incmdlog" |tee -a $logdir/$jobname.log
 trap 'after_run 1' 1 2 3 9 15
 
 ## run
-rake -f $rakefile dir="$dir" in="$in" jackdb="$jackdb" hhdb="$hhdb" iter="$iter" incE="$incE" incdomE="$incdomE" nreport="$nreport" \
+rake -f $rakefile dir="$dir" in="$in" mode="$mode" jackdb="$jackdb" hhdb="$hhdb" iter="$iter" incE="$incE" incdomE="$incdomE" nreport="$nreport" \
 	evalue="$evalue" pvalue="$pvalue" prob="$prob" queue="$queue" ncpus="$ncpus" wtime="$wtime" 2>&1 |tee -a $logdir/$jobname.log
 st=$(( ${PIPESTATUS[0]} + ${PIPESTATUS[1]} ))
 after_run $st
